# Generated by Django 5.1.7 on 2026-02-12 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='payment_method',
            field=models.CharField(choices=[('UPI', 'UPI'), ('CREDIT_CARD', 'Credit Card'), ('SLICE_BORROW', 'Slice Borrow'), ('CRED_CASH', 'Cred Cash'), ('EMI', 'EMI'), ('CASH', 'Cash'), ('OTHER', 'Other')], default='CASH', max_length=20),
        ),
        migrations.AddField(
            model_name='expense',
            name='transaction_type',
            field=models.CharField(choices=[('EXPENSE', 'Expense'), ('RECEIVABLE', 'Receivable')], default='EXPENSE', max_length=20),
        ),
    ]
