# Generated by Django 5.1.7 on 2026-02-12 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_expense_payee_username_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='related_receivable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payables', to='expenses.expense'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='transaction_type',
            field=models.CharField(choices=[('EXPENSE', 'Expense'), ('RECEIVABLE', 'Receivable'), ('PAYABLE', 'Payable')], default='EXPENSE', max_length=20),
        ),
    ]
